#!/bin/bash

account="$1"

if grep -q "[${account}]" ~/.aws/credentials; then
    sed -i "/\[$account\]/,/^$/d" ~/.aws/credentials
fi
if grep -q "[${account}\-west]" ~/.aws/credentials; then
    sed -i "/\[${account}-west\]/,/^$/d" ~/.aws/credentials
fi

if ! grep -q "${account}" ~/.aws/config; then
    echo "[profile ${account}]" >> ~/.aws/config
    echo "region = us-east-2" >> ~/.aws/config
    echo "output = json" >> ~/.aws/config
    echo "" >> ~/.aws/config
fi
if ! grep -q "${account}-west" ~/.aws/config; then
    echo "[profile ${account}-west]" >> ~/.aws/config
    echo "region = us-west-2" >> ~/.aws/config
    echo "output = json" >> ~/.aws/config
    echo "" >> ~/.aws/config
fi

xclip -selection clipboard -o | sed "s/\[.*\]/[${account}]/g" >> ~/.aws/credentials
echo "" >> ~/.aws/credentials
echo "" >> ~/.aws/credentials

xclip -selection clipboard -o | sed "s/\[.*\]/[${account}-west]/g" >> ~/.aws/credentials
echo "" >> ~/.aws/credentials
echo "" >> ~/.aws/credentials
